# yaml-language-server: $schema=https://testingcf.jsdelivr.net/gh/StageDog/tavern_sync/dist/schema/settings.zh.json

# 在此填入 user 名称, 提示词中如果有这个名字则会被替换成 <user> 宏
user名称: 青空黎

# 在此填入新的"世界书"或"预设"配置
配置:
  # 配置名称, 可以和酒馆中的不同. 你使用脚本时需要填写配置名称来指出用哪个配置, 因此尽量配置名称尽量简单点方便填写
  恩赐之主:
    # 类型可以是"世界书"或"预设"
    类型: 世界书

    # 在酒馆中这个"世界书"或"预设"叫什么
    酒馆中的名称: 恩赐之主

    # 这个世界书或预设的等效配置文件要提取到本地哪个文件中, 可以是绝对路径或相对于本文件的相对路径
    # 如果不满足路径格式将会报错
    # - 绝对路径: 如 Windows 中, 想将世界书提取到 C 盘"恩赐之主"文件夹中, 则填入 `C:/恩赐之主/恩赐之主`
    # - 相对路径:
    #   - 想将世界书配置文件提取到本文件相同的文件夹中, 则填入 `./恩赐之主` 或 `恩赐之主`
    #   - 想将世界书配置文件提取到本文件所在文件夹的子文件夹"世界书"中, 则填入 `./世界书/恩赐之主` 或 `世界书/恩赐之主`
    #   - 想将世界书配置文件提取到本文件所在文件夹的父文件夹中, 则填入 `../恩赐之主
    本地文件路径: ./世界书/恩赐之主

    # 当使用 `node tavern_sync.mjs push 配置名称 -e` 导出能直接由酒馆界面导入的世界书/预设文件时, 要将它存放在哪个文件中
    # 你也可以直接删去下面一行不填, 则默认会导出到本地文件路径的同目录下
    导出文件路径: ./世界书/恩赐之主
